import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import AppSidebar from '@/components/layout/app-sidebar';
import SideAndTopLayout from '@/components/layout/side-and-top-layout';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="de">
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-indigo-50 antialiased`}
            >
                <SideAndTopLayout>{children}</SideAndTopLayout>
            </body>
        </html>
    );
}
